# Generated by Django 4.2.4 on 2023-10-28 01:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Respuesta', max_length=200, verbose_name='Nombre de la respuesta')),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radiobutton', 'Radio Button')], default='checkbox', max_length=12)),
                ('text', models.TextField(max_length=610, verbose_name='Texto de la respuesta')),
                ('orderAnswer', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('excludedPolicies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Política 1'), (2, 'Política 2'), (3, 'Política 3'), (4, 'Política 4'), (5, 'Política 5'), (6, 'Política 6'), (7, 'Política 7'), (8, 'Política 8'), (9, 'Política 9'), (10, 'Política 10'), (11, 'Política 11'), (12, 'Política 12'), (13, 'Política 13'), (14, 'Política 14'), (15, 'Política 15'), (16, 'Política 16'), (17, 'Política 17'), (18, 'Política 18'), (19, 'Política 19'), (20, 'Política 20'), (21, 'Política 21'), (22, 'Política 22'), (23, 'Política 23'), (24, 'Política 24'), (25, 'Política 25'), (26, 'Política 26'), (27, 'Política 27'), (28, 'Política 28'), (29, 'Política 29'), (30, 'Política 30'), (31, 'Política 31'), (32, 'Política 32')], default=[1], max_length=100, null=True, verbose_name='Políticas excluidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Política', max_length=200, verbose_name='Nombre de la política')),
                ('category', models.CharField(default='Categoría', max_length=200, verbose_name='Categoría')),
                ('orderPolicy', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policyCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policyUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Política',
                'verbose_name_plural': 'Políticas',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del proyecto')),
                ('startDate', models.DateField(verbose_name='Fecha inicio')),
                ('endDate', models.DateField(verbose_name='Fecha fin')),
                ('numQuestion', models.PositiveIntegerField(default=1, verbose_name='Número de pregunta')),
                ('excludedPolicies', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Política 1'), (2, 'Política 2'), (3, 'Política 3'), (4, 'Política 4'), (5, 'Política 5'), (6, 'Política 6'), (7, 'Política 7'), (8, 'Política 8'), (9, 'Política 9'), (10, 'Política 10'), (11, 'Política 11'), (12, 'Política 12'), (13, 'Política 13'), (14, 'Política 14'), (15, 'Política 15'), (16, 'Política 16'), (17, 'Política 17'), (18, 'Política 18'), (19, 'Política 19'), (20, 'Política 20'), (21, 'Política 21'), (22, 'Política 22'), (23, 'Política 23'), (24, 'Política 24'), (25, 'Política 25'), (26, 'Política 26'), (27, 'Política 27'), (28, 'Política 28'), (29, 'Política 29'), (30, 'Política 30'), (31, 'Política 31'), (32, 'Política 32')], max_length=100, null=True, verbose_name='Políticas excluidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projectUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Documento', max_length=200, verbose_name='Nombre del documento')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pregunta', max_length=200, verbose_name='Nombre de la pregunta')),
                ('text', models.TextField(max_length=500, verbose_name='Texto de la pregunta')),
                ('orderQuestion', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radiobutton', 'Radio Button')], default='checkbox', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='ProjectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAnswer', models.BooleanField(default=True)),
                ('orderProjectQuestion', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('answer', models.ManyToManyField(to='core.answer')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_questionCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Proyecto')),
                ('question', models.ManyToManyField(to='core.question')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_questionUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyecto - Preguntas',
                'verbose_name_plural': 'Proyectos - Preguntas',
            },
        ),
        migrations.CreateModel(
            name='ProjectPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.BooleanField(default=False)),
                ('orderProjectPolicy', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_policyCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('policy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.policy', verbose_name='Política')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Proyecto')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_pUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Proyecto - Políticas',
                'verbose_name_plural': 'Proyectos - Políticas',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='answer',
            name='updatedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
    ]
