# Generated by Django 4.2.4 on 2023-10-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='excludedPolicies',
        ),
    ]
