# Generated by Django 4.2.4 on 2023-10-28 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_text_createdby_text_created_at_text_ordertext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpolicy',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
