# Generated by Django 4.2.4 on 2023-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectpolicy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='fileName',
            field=models.CharField(default='Archivo', max_length=200, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='text',
            name='name',
            field=models.CharField(default='Política', max_length=200, verbose_name='Nombre de la política'),
        ),
    ]
