# Generated by Django 4.2.4 on 2023-09-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Nombre del proyecto'),
        ),
    ]
