# Generated by Django 4.2.4 on 2023-10-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_text_filename_alter_text_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpolicy',
            name='fileName',
            field=models.CharField(default='Archivo', max_length=200, verbose_name='Nombre del archivo'),
        ),
    ]
