# Generated by Django 4.2.4 on 2023-10-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_projectpolicy_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpolicy',
            name='type',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('deprecado', 'Deprecado')], default='borrador', max_length=12),
        ),
    ]
