# Generated by Django 4.2.4 on 2023-10-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_type_projectpolicy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpolicy',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Aprobado', 'Aprobado'), ('Deprecado', 'Deprecado')], default='Borrador', max_length=12, verbose_name='Estado'),
        ),
    ]
