# Generated by Django 4.2.4 on 2023-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_project_updatedby_alter_project_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Pregunta', max_length=200, verbose_name='Nombre de la pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Texto de la pregunta'),
        ),
    ]
