# Generated by Django 4.2.4 on 2023-09-23 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_question_name_alter_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Respuesta', max_length=200, verbose_name='Nombre de la respuesta')),
                ('text', models.TextField(max_length=500, verbose_name='Texto de la respuesta')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answerUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
