# Generated by Django 4.2.4 on 2023-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_projectpolicy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpolicy',
            name='status',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Aprobado', 'Aprobado'), ('Descontinuado', 'Descontinuado')], default='Borrador', max_length=13, verbose_name='Estado'),
        ),
    ]
