# Generated by Django 4.2.4 on 2023-09-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=10),
        ),
    ]
