# Generated by Django 4.2.4 on 2023-10-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_control_answer_excludedcontrols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.CharField(default='Descripción', max_length=450, verbose_name='Descripción Breve'),
        ),
    ]
