# Generated by Django 4.2.4 on 2023-09-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='status',
        ),
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('radiobutton', 'Radio Button')], default='checkbox', max_length=12),
        ),
    ]
