# Generated by Django 4.2.4 on 2023-09-25 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_remove_answer_status_answer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numQuestion',
            field=models.IntegerField(null=True, verbose_name='Número de pregunta'),
        ),
        migrations.CreateModel(
            name='project_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAnswer', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='TRUE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('answer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.answer', verbose_name='Respuesta')),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_questionCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.project', verbose_name='Proyecto')),
                ('question', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Pregunta')),
                ('updatedBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_questionUpdatedBy', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
