# Generated by Django 4.2.4 on 2023-09-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_project_question_projectquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
