# Generated by Django 4.2.4 on 2023-10-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0020_pregunta_question_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_question', to='contenttypes.contenttype', verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.answer', verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='core.question', verbose_name='Pregunta'),
        ),
    ]
