# Generated by Django 4.2.4 on 2023-10-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_pregunta_projectquestion_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
    ]
