# Generated by Django 4.2.4 on 2023-10-02 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_projectquestion_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
    ]
