# Generated by Django 4.2.4 on 2023-10-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_projectquestion_project_projectquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='name',
            field=models.CharField(default='None - None', max_length=200, verbose_name='Nombre del proyecto'),
        ),
    ]
