# Generated by Django 4.2.4 on 2023-10-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_projectquestion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='id',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='object_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
