# Generated by Django 4.2.4 on 2023-10-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_projectquestion_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
    ]
