# Generated by Django 4.2.4 on 2023-10-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_projectquestion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='object_id',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
