# Generated by Django 4.2.4 on 2023-10-02 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_projectquestion_object_id_projectquestion_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
    ]
