# Generated by Django 4.2.4 on 2023-10-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_projectquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
    ]
