# Generated by Django 4.2.4 on 2023-10-02 04:15

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_projectquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='object_id',
            field=models.BigIntegerField(default=builtins.id, verbose_name='ID'),
        ),
    ]
