# Generated by Django 4.2.4 on 2023-10-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_projectquestion_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
    ]
