# Generated by Django 4.2.4 on 2023-10-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_projectquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='name',
        ),
    ]
