# Generated by Django 4.2.4 on 2023-10-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_remove_projectquestion_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectquestion',
            options={'verbose_name': 'Proyecto - Respuestas', 'verbose_name_plural': 'Projectos - Respuestas'},
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='core.answer', verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='userAnswer',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='TRUE', max_length=12),
        ),
    ]
