# Generated by Django 4.2.4 on 2023-10-02 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_projectquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectanswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_project', to='core.answer', verbose_name='Respuesta'),
        ),
    ]
