# Generated by Django 4.2.4 on 2023-10-02 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_projectanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquestion',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_project', to='core.question', verbose_name='Pregunta'),
        ),
    ]
