# Generated by Django 4.2.4 on 2023-10-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_projectquestion_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAnswer',
        ),
    ]
