# Generated by Django 4.2.4 on 2023-10-02 17:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_project_numquestion_alter_project_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Respuesta 1'), ('2', 'Respuesta 2'), ('3', 'Respuesta 3'), ('4', 'Respuesta 4'), ('5', 'Respuesta 5')], default='1, 2, 3, 4, 5, ', max_length=11),
        ),
    ]
