# Generated by Django 4.2.4 on 2023-10-02 17:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_project_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1, 2, 3, 4, 5, ', max_length=11),
        ),
    ]
