# Generated by Django 4.2.4 on 2023-10-05 03:50

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_project_question1'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='Answer',
            field=models.ManyToManyField(to='core.answer'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='userAnswer',
            field=models.BooleanField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], default='TRUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1,2,3,4,5', max_length=11),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='projectQuestionProject', to='core.project', verbose_name='Proyecto'),
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='question',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
