# Generated by Django 4.2.4 on 2023-10-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_projectquestion_answer_projectquestion_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='question1',
        ),
    ]
