# Generated by Django 4.2.4 on 2023-10-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_project_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquestion',
            name='userAnswer',
            field=models.BooleanField(choices=[('verdadero', 'Verdadero'), ('falso', 'Falso')], default='TRUE', max_length=12),
        ),
    ]
