# Generated by Django 4.2.4 on 2023-10-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_projectquestion_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='order',
        ),
    ]
