# Generated by Django 4.2.4 on 2023-10-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_projectquestion_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='order',
            new_name='orderAnswer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='order',
            new_name='orderQuestion',
        ),
        migrations.DeleteModel(
            name='ProjectAnswer',
        ),
    ]
