# Generated by Django 4.2.4 on 2023-10-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_rename_order_answer_orderanswer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
    ]
