# Generated by Django 4.2.4 on 2023-10-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_remove_projectquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='Answer',
            field=models.ManyToManyField(to='core.answer'),
        ),
        migrations.AddField(
            model_name='projectquestion',
            name='question',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
