# Generated by Django 4.2.4 on 2023-10-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_projectquestion_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectquestion',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectquestion',
            name='question',
        ),
    ]
