# Generated by Django 4.2.4 on 2023-10-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_projectquestion_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectQuestion',
        ),
    ]
