# Generated by Django 4.2.4 on 2023-10-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_projectquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='question',
            field=models.ManyToManyField(to='core.question'),
        ),
    ]
