# Generated by Django 4.2.4 on 2023-10-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_projectquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='answer',
            field=models.ManyToManyField(to='core.answer'),
        ),
    ]
