# Generated by Django 4.2.4 on 2023-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_rename_orderquestion_question_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
