# Generated by Django 4.2.4 on 2023-10-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
