# Generated by Django 4.2.4 on 2023-10-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_remove_answer_orderanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='orderAnswer',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='question',
            name='orderQuestion',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
    ]
