# Generated by Django 4.2.4 on 2023-10-06 01:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_answer_orderanswer_question_orderquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='question1',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1,2,3,4,5', max_length=11),
        ),
    ]
