# Generated by Django 4.2.4 on 2023-10-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_project_question1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='question1',
        ),
    ]
