# Generated by Django 4.2.4 on 2023-10-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_remove_project_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectquestion',
            name='userAnswer',
            field=models.BooleanField(default=True),
        ),
    ]
