# Generated by Django 4.2.4 on 2023-10-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_projectquestion_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectquestion',
            name='orderProjectQuestion',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
