# Generated by Django 4.2.4 on 2023-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_projectquestion_orderprojectquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='orderAnswer',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='project',
            name='numQuestion',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de pregunta'),
        ),
        migrations.AlterField(
            model_name='projectquestion',
            name='orderProjectQuestion',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='question',
            name='orderQuestion',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
