# Generated by Django 4.2.4 on 2023-10-07 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_answer_orderanswer_alter_project_numquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio'),
        ),
    ]
