# Generated by Django 4.2.4 on 2023-10-07 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha inicio'),
        ),
    ]
