# Generated by Django 4.2.4 on 2023-10-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(verbose_name='Fecha inicio'),
        ),
    ]
